### ISSUE TITLE
Norwegian (nn-NO) is not supported 

### ISSUE THREAD

**Issue by PujaSrinandan** [microsoft/Multilingual-App-Toolkit#17]
We are using the Microsoft multilingual toolkit for translation, the language Norwegian (nn-NO) is not supported i.e. the labels, error, messages etc. are not getting translated to Norwegian (nn-NO) language.

**Comment by joshftb** [comment]
![image](https://user-images.githubusercontent.com/90873829/229989704-3f6a1581-306b-45a0-bc1d-741feb82f36f.png)
Hi, can you try searching for Norwegian in the translation languages window (Multilingual App Toolkit -> Add translation languages)? Please refer to the image above.

**Comment by PujaSrinandan** [comment]
We are looking for Norwegian for (Nynorsk), could you let us know if its supported by this tool.

**Comment by joshftb** [comment]
Hi, it is not supported by Microsoft Translator. But you can use nn-NO with language portal (4th option from bottom in the screenshot).
