### ISSUE TITLE
No Support for DLL's

### ISSUE THREAD

**Issue by RealDotNetDave** [microsoft/Multilingual-App-Toolkit#20]
After learning how to use the toolkit, as many articles state, what I have done in the past is to put all the resources for a solution in a DLL assembly for reuse by any project. When I tried to **Enable selection**, I got the following message:

` Project 'Globalization.Resources' was not enabled - it is not a supported project type.`

Why can't I use the toolkit in a DLL? This is a great tool, but I cannot use it for projects like this.

**Comment by joshftb** [comment]
The structure of DLLs is more complex compared to resource files. This makes parsing and regenerating them a very difficult task. Please consider using resx or resw instead.
