### ISSUE TITLE
Cannot change the display language on the Editor

### ISSUE THREAD

**Issue by imchiman** [microsoft/Multilingual-App-Toolkit#22]
Cannot change the display language on the Editor, the Editor opened as system locale but the translation is really poor, I perfer to use other display languages such as English instead of my system language.

**Comment by joshftb** [comment]
Hi, sorry to hear about the translation quality. Can you try downloading the most recent version of the editor? In previous releases, only machine translation was used. 

In the meantime, we will add this to the roadmap.
