### ISSUE TITLE
There are too many errors in the Chinese UI text translated by the machine

### ISSUE THREAD

**Issue by LaplaceStudio** [microsoft/Multilingual-App-Toolkit#27]
The UI text of the tool seems to be machine translated, which is very inaccurate and has many errors (such as translating resource status "state" into "州" and "save" into "救",etc.). Can you provide the simplified Chinese XLF file of the tool for optimizing Chinese translation.

**Comment by joshftb** [comment]
While the tool uses Microsoft Translator for machine translations, we cannot guarantee their quality. To ensure accuracy and context sensitivity, we recommend having the translations reviewed by a human translator.
