### ISSUE TITLE
Project 'WPF .net 7' was not enabled - it is not a supported project type ?

### ISSUE THREAD

**Issue by wstaelens** [microsoft/Multilingual-App-Toolkit#31]
Can't seem to enable MAT for a WPF .net 7 project.

Using VS 2022 Pro 17.9.5 on windows 10 x64.

MAT 4.2.3 extension installed.

Others seem to have the same problem: https://stackoverflow.com/questions/75547404/how-to-enable-multilingual-toolkit-for-wpf-application-net-7-0-type-project

**Comment by joshftb** [comment]
Thanks for reporting this. We will look into it. Do you happen to have a sample project that this issue repros on?

**Comment by joshftb** [comment]
We tested the extension on a WPF .NET 7 project and found that we could enable it.

As a prerequisite to enabling MAT resource files will need to be present. Assuming that condition is met, you should see the following in the MAT output pane:
 
![image](https://github.com/microsoft/Multilingual-App-Toolkit/assets/90873829/e4d1a18e-44fd-40ba-88bf-c548a95b63b8)


Then, you can enable MAT from Tools -> “Multilingual App Toolkit” -> “Enable Selection”
 
![image](https://github.com/microsoft/Multilingual-App-Toolkit/assets/90873829/b506526d-a483-4b66-a379-a39a8ea64b02)



You will be prompted to set the source language, after which you may click save.

 
![image](https://github.com/microsoft/Multilingual-App-Toolkit/assets/90873829/533e943f-b807-46cc-b109-29a56dab2806)



When the source language is set the project file should unload and reload. Then, you should see the following output indicating that the tool was enabled:

 
![image](https://github.com/microsoft/Multilingual-App-Toolkit/assets/90873829/4420df40-a7ce-406d-8c1c-67b8ddfb055c)

**Comment by joshftb** [comment]
Marking as closed. Feel free to re-open as needed.
