### ISSUE TITLE
Could not install the extension (version 4.1.1)

### ISSUE THREAD

**Issue by LeoLiXX** [microsoft/Multilingual-App-Toolkit#8]
Anybody meets the same trouble with me?
I have tried update several build agents with the latest extension, v4.1.1, but seems always fails.

Part of the abnormal information was noticed like the following:

5/17/2022 11:15:45 AM - Beginning to install extension to Visual Studio Enterprise 2022...
5/17/2022 11:15:49 AM - Skipping non-applicable package Microsoft.VisualStudio.Debugger.DbgHelp.Win8: The current OS Version '10.0.17763.0' is not in the supported version range '[6.1,6.3]'.
5/17/2022 11:15:49 AM - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: The current OS Version '10.0.17763.0' is not in the supported version range '[6.1,6.3]'.
5/17/2022 11:15:49 AM - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: The current OS Version '10.0.17763.0' is not in the supported version range '[6.1,6.3]'.
5/17/2022 11:15:50 AM - Skipping non-applicable package Microsoft.VisualStudio.NuGet.PowershellBindingRedirect: The current OS Version '10.0.17763.0' is not in the supported version range '[6.1,6.2)'.
5/17/2022 11:15:50 AM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.7: The current OS Version '10.0.17763.0' is not in the supported version range '[6.1,6.2)'.
5/17/2022 11:15:50 AM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.8: The current OS Version '10.0.17763.0' is not in the supported version range '[6.2,6.3)'.
5/17/2022 11:15:50 AM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.81: The current OS Version '10.0.17763.0' is not in the supported version range '[6.3,6.4)'.
5/17/2022 11:15:51 AM - Skipping non-applicable package Microsoft.Net.4.8.KB5003306: The current OS Version '10.0.17763.0' is not in the supported version range '[10.0.18362,10.0.18363]'.
5/17/2022 11:15:51 AM - Skipping non-applicable package Microsoft.Net.4.8.KB5003304: The current OS Version '10.0.17763.0' is not in the supported version range '[10.0.19041,10.0.19044]'.
5/17/2022 11:15:51 AM - Skipping non-applicable package Microsoft.Net.4.8.KB5003793: The current OS Version '10.0.17763.0' is not in the supported version range '[10.0.20279,10.0.20348]'.
5/17/2022 11:15:51 AM - Skipping non-applicable package Microsoft.Net.4.8.KB5003792: The current OS Version '10.0.17763.0' is not in the supported version range '10.0.21290'.
5/17/2022 11:15:51 AM - Skipping non-applicable package Microsoft.DiagnosticsHub.KB2882822.Win7: The current OS Version '10.0.17763.0' is not in the supported version range '[6.1,6.2)'.
5/17/2022 11:15:52 AM - Skipping non-applicable package Microsoft.Windows.D3DCompiler.Msu.Win7: The current OS Version '10.0.17763.0' is not in the supported version range '[6.1,6.2)'.
5/17/2022 11:15:52 AM - Skipping non-applicable package Microsoft.Net.4.6.FullRedist: The current OS Version '10.0.17763.0' is not in the supported version range '[6.1.1,6.4)'.
5/17/2022 11:15:52 AM - Skipping non-applicable package Microsoft.Ancm.IIS.Msi: Required conditions are not satisfied: IISCoreWebEngineInstalledx64 And IISW3SvcInstalledx64
5/17/2022 11:15:52 AM - Skipping non-applicable package Microsoft.Ancmv2.IIS.Msi: Required conditions are not satisfied: IISCoreWebEngineInstalledx64 And IISW3SvcInstalledx64
5/17/2022 11:15:53 AM - Skipping non-applicable package Microsoft.Azure.PowerShell: Required conditions are not satisfied: Not Powershell5
5/17/2022 11:15:55 AM - Skipping non-applicable package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu: The current OS Version '10.0.17763.0' is not in the supported version range '(,6.2)'.
5/17/2022 11:16:09 AM - Package 'MultilingualAppToolkit.Microsoft.bc7f20d6-73ff-4f4d-8084-eb773575c8a5,version=4.1.1' failed to install. System.IO.IOException: The file 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Multilingual App Toolkit\Microsoft.Multilingual.Build.BuildTaskTargets.dll' already exists.
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.<InstallCoreInternal>g__install|31_1(PackagePart part, Boolean saveExtensionManifest, <>c__DisplayClass31_0& , <>c__DisplayClass31_1& , <>c__DisplayClass31_2& , <>c__DisplayClass31_3& , <>c__DisplayClass31_4& )

Any suggestion?

**Comment by LeoLiXX** [comment]
Additional information with this issue
1. VS2022 17.1.0 seems will fails to install this extension. After update to the latest version (17.2.1), I can have it installed on my machine (Win10)
2. But our build agent uses Windows Server 2019, and I can see even I update the VS2022 to the latest version, I will always get error when installing the tool.
Anything we can do to have the extension installed correctly?

**Comment by joshftb** [comment]
Hi,

- Verify that the extension is uninstalled. 
- Then remove the  'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Multilingual App Toolkit' directory. (This was causing the System.IO.IOException above)
- After these two steps, try installing again.
